### ISSUE TITLE
Great Idea but...

### ISSUE THREAD

**Issue by keithmancuso** [WilliamIsted/CraftPlural#2]
Hey great idea for a plugin but it only works for words that pluralize with an s at the end, but of course theres lots of more complex scenarios.

Would you consider integrating some kind of pluralize library into it?  

Some examples include:
https://gist.github.com/tbrianjones/ba0460cc1d55f357e00b 

OR maybe a simplier way to do it would be to have ot just be a wrapper around this php function
http://php.net/manual/en/function.ngettext.php

that lets the user pass both the singular and plural versions of the word?

Just some thoughts

**Comment by WilliamIsted** [comment]
Thanks for your feedback, I believe this can be achieved using the following method:

`{{ 1 | plural('result', 'foobars') }} found.`

Where the first argument is the singular, and the second argument defines the word that should be returned if it should be pluralised (defaults to 's' if omitted).

If this is not the case; if you could provide an example of usage I'll be happy to take a closer look. The [`ngettext`](http://php.net/manual/en/function.ngettext.php) function does looks pretty handy.

**Comment by keithmancuso** [comment]
Ah! Nice you are totally right missed that! That's exactly what I needed!
Thanks
